version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - API_IP=${API_IP}
    ports:
      - "8443:443"   # HTTPS
      - "8080:80"     # HTTP (for redirect to HTTPS)
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - API_IP=${API_IP}
  backend:
    build:
      context: ./backend
    networks:
      - app-network
    environment:
      - DB_PATH=${DB_PATH}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
    volumes:
      - /goinfre:/goinfre # Mount goinfre directory for database persistence
    restart: unless-stopped

networks:
  app-network:
    driver: bridge